name: stable_horde_flutter
description: An unofficial Flutter client for the Stable Horde.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.4+11

environment:
  sdk: '>=2.17.3 <3.0.0'
  flutter: '>=3.3.7'

dependencies:
  cached_network_image: ^3.0.0

  flutter:
    sdk: flutter

  firebase_analytics: ^9.1.2
  firebase_core: ^1.13.1
  firebase_remote_config: ^2.0.20

  google_fonts: ^3.0.1

  intl: ^0.17.0

  url_launcher: ^6.1.6

  image: ^3.2.0

  sentry_flutter: ^6.18.1

  shared_preferences: ^2.0.5
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

  path_provider: ^2.0.11



dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
