name: stable_horde_flutter
description: An unofficial Flutter client for the Stable Horde.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.1.2+23

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.7.1"

dependencies:
  cached_network_image: ^3.2.3
  collection: ^1.16.0
  dotted_border: ^2.0.0+3
  device_info: ^2.0.3
  expandable: ^5.0.1
  firebase_analytics: ^10.0.8
  firebase_core: ^2.4.0
  firebase_remote_config: ^3.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  http: ^0.13.5
  image: ^3.2.2
  image_picker: ^0.8.6
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  package_info: ^2.0.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  sentry_flutter: ^6.18.1
  share_plus: ^6.3.1
  shared_preferences: ^2.0.5
  url_launcher: ^6.1.6
  native_exif: ^0.4.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/cat.jpg
    - assets/images/ios_icon.jpg
    - assets/images/knollingcase.jpg

    - assets/vector_drawables/box.svg
